### ISSUE TITLE
Unresolved reference: notIn报错

### ISSUE THREAD

**Issue by wjxjasin** [KAMO030/MyBatis-Flex-Kotlin#13]
使用notIn时，编译直接报错Unresolved reference: notIn，表示无法引用依赖
相关写法
.where(OrderWaybill::waybillNumber.eq(waybillNumber).and(OrderWaybill::waybillStatus.notIn(notInStatusList)))
使用QueryWrapper则正常

**Comment by KAMO030** [comment]
请问使用的是Kotlin相关的方法吗?

**Comment by wjxjasin** [comment]
版本：
![image](https://github.com/user-attachments/assets/39a5c4e7-8170-4f72-ac6f-e3735671d297)
相关的写法
val update = UpdateChain.of(OrderWaybill::class.java)
                .set(OrderWaybill::waybillStatus, 1)
                .where(OrderWaybill::waybillNumber.eq(waybillNumber)
                .and(OrderWaybill::waybillStatus.notIn(notInStatusList)))
                .update()

**Comment by KAMO030** [comment]
有引入核心库嘛?

**Comment by wjxjasin** [comment]
![image](https://github.com/user-attachments/assets/8ff5a043-0829-46c5-9181-0b8887d4e620)
只有这些相关的flex

**Comment by KAMO030** [comment]
myBatis-flex-kotlin这个依赖去掉试试,这是以前的现在只用extensions就好了

**Comment by wjxjasin** [comment]
还是不行

**Comment by wjxjasin** [comment]
可以了

**Comment by wjxjasin** [comment]
感谢

**Comment by flyGetHu** [comment]
那具体这个插件是做什么的

**Comment by KAMO030** [comment]
@flyGetHu 可以看看这个:[kotlinGradlePlugin](https://github.com/KAMO030/MyBatis-Flex-Kotlin/blob/main/docs/kotlinGradlePlugin.md)

**Comment by flyGetHu** [comment]
> @flyGetHu 可以看看这个:[kotlinGradlePlugin](https://github.com/KAMO030/MyBatis-Flex-Kotlin/blob/main/docs/kotlinGradlePlugin.md)

明白  感谢作者

**Comment by wjxjasin** [comment]
这个问题能修复么。去掉插件之后引发了其他bug了，比如 data class 问题

**Comment by KAMO030** [comment]
> 这个问题能修复么。去掉插件之后引发了其他bug了，比如 data class 问题

如果是新项目的话建议使用gradle来开发kotlin项目，实在改不动可以参考下kotlin官方文档配置[noarg](https://kotlinlang.org/docs/no-arg-plugin.html#gradle)和[allopen](https://kotlinlang.org/docs/all-open-plugin.html)插件的mavem配置方法
