### ISSUE TITLE
关于分页查询功能的使用文档

### ISSUE THREAD

**Issue by RisenMyth** [KAMO030/MyBatis-Flex-Kotlin#2]
**问题描述：** 使用它实现普通查询的时候很好用，但在实际业务场景中需要进行分页查询，我在README中没有找到相关的使用方式，是没有提供相关功能吗？

**环境：**

- Kotlin：1.8.22
- mybatis-flex-spring-boot-starter：1.7.0
- mybatis-flex-kotlin：1.0.1

**Comment by IkuzItsuki** [comment]
query支持，filter暂时不支持，query直接在花括号里调用limit方法就好了
